interface TemplateFile {
  path: string;
  content: string;
}

function lines(...value: string[]): string {
  return `${value.join('\n')}\n`;
}

export function getExpressAuthFiles(name: string): TemplateFile[] {
  return [
    {
      path: 'src/server.ts',
      content: lines(
        "import 'dotenv/config';",
        "import { app } from '@/app';",
        "",
        "const port = Number(process.env.PORT ?? 3001);",
        "",
        "app.listen(port, () => {",
        `  console.log('${name} running on http://localhost:' + port);`,
        "});",
      ),
    },
    {
      path: 'src/app.ts',
      content: lines(
        "import express from 'express';",
        "import cors from 'cors';",
        "import { router } from '@/routes/index.route';",
        "import { errorHandler } from '@/middleware/error.middleware';",
        "",
        "export const app = express();",
        "",
        "app.use(cors());",
        "app.use(express.json());",
        "app.use(express.urlencoded({ extended: true }));",
        "",
        "app.get('/health', (_req, res) => {",
        "  res.json({ status: 'ok' });",
        "});",
        "",
        "app.use('/api', router);",
        "app.use(errorHandler);",
      ),
    },
    {
      path: 'src/routes/index.route.ts',
      content: lines(
        "import { Router } from 'express';",
        "import { authRouter } from '@/routes/auth.route';",
        "",
        "export const router = Router();",
        "",
        "router.use('/auth', authRouter);",
      ),
    },
    {
      path: 'src/routes/auth.route.ts',
      content: lines(
        "import { Router } from 'express';",
        "import { AuthController } from '@/controllers/auth.controller';",
        "import { authMiddleware } from '@/middleware/auth.middleware';",
        "import { validate } from '@/middleware/validate.middleware';",
        "import {",
        "  forgotPasswordSchema,",
        "  loginSchema,",
        "  registerSchema,",
        "  resetPasswordSchema,",
        "  twoFactorSchema,",
        "  verifyEmailSchema,",
        "} from '@/schemas/auth.schema';",
        "",
        "const controller = new AuthController();",
        "export const authRouter = Router();",
        "",
        "authRouter.post('/register', validate(registerSchema), controller.register);",
        "authRouter.post('/login', validate(loginSchema), controller.login);",
        "authRouter.post('/forgot-password', validate(forgotPasswordSchema), controller.forgotPassword);",
        "authRouter.post('/reset-password', validate(resetPasswordSchema), controller.resetPassword);",
        "authRouter.post('/verify-email', validate(verifyEmailSchema), controller.verifyEmail);",
        "authRouter.post('/2fa/setup', authMiddleware, controller.setupTwoFactor);",
        "authRouter.post('/2fa/verify', authMiddleware, validate(twoFactorSchema), controller.verifyTwoFactor);",
      ),
    },
    {
      path: 'src/controllers/auth.controller.ts',
      content: lines(
        "import { NextFunction, Request, Response } from 'express';",
        "import { AuthService } from '@/services/auth.service';",
        "",
        "const authService = new AuthService();",
        "",
        "export class AuthController {",
        "  register = async (req: Request, res: Response, next: NextFunction) => {",
        "    try {",
        "      const result = await authService.register(req.body);",
        "      res.status(201).json(result);",
        "    } catch (err) {",
        "      next(err);",
        "    }",
        "  };",
        "",
        "  login = async (req: Request, res: Response, next: NextFunction) => {",
        "    try {",
        "      const result = await authService.login(req.body);",
        "      res.json(result);",
        "    } catch (err) {",
        "      next(err);",
        "    }",
        "  };",
        "",
        "  forgotPassword = async (req: Request, res: Response, next: NextFunction) => {",
        "    try {",
        "      const result = await authService.forgotPassword(req.body);",
        "      res.json(result);",
        "    } catch (err) {",
        "      next(err);",
        "    }",
        "  };",
        "",
        "  resetPassword = async (req: Request, res: Response, next: NextFunction) => {",
        "    try {",
        "      const result = await authService.resetPassword(req.body);",
        "      res.json(result);",
        "    } catch (err) {",
        "      next(err);",
        "    }",
        "  };",
        "",
        "  verifyEmail = async (req: Request, res: Response, next: NextFunction) => {",
        "    try {",
        "      const result = await authService.verifyEmail(req.body);",
        "      res.json(result);",
        "    } catch (err) {",
        "      next(err);",
        "    }",
        "  };",
        "",
        "  setupTwoFactor = async (req: Request, res: Response, next: NextFunction) => {",
        "    try {",
        "      const result = await authService.setupTwoFactor(req.user!.id);",
        "      res.json(result);",
        "    } catch (err) {",
        "      next(err);",
        "    }",
        "  };",
        "",
        "  verifyTwoFactor = async (req: Request, res: Response, next: NextFunction) => {",
        "    try {",
        "      const result = await authService.verifyTwoFactor(req.user!.id, req.body.code);",
        "      res.json(result);",
        "    } catch (err) {",
        "      next(err);",
        "    }",
        "  };",
        "}",
      ),
    },
    {
      path: 'src/services/auth.service.ts',
      content: lines(
        "import bcrypt from 'bcrypt';",
        "import crypto from 'node:crypto';",
        "import { EmailService } from '@/services/email.service';",
        "import { prisma } from '@/config/prisma';",
        "import type { LoginInput, RegisterInput } from '@/schemas/auth.schema';",
        "import { generateToken } from '@/utils/token.util';",
        "import { setupTwoFactor, verifyTwoFactorToken } from '@/utils/two-factor.util';",
        "",
        "const emailService = new EmailService();",
        "",
        "export class AuthService {",
        "  async register(data: RegisterInput) {",
        "    const existing = await prisma.user.findUnique({ where: { email: data.email } });",
        "    if (existing) throw Object.assign(new Error('Email already registered'), { status: 400 });",
        "",
        "    const hashedPassword = await bcrypt.hash(data.password, 12);",
        "    const emailVerificationToken = crypto.randomBytes(32).toString('hex');",
        "",
        "    const user = await prisma.user.create({",
        "      data: {",
        "        name: data.name,",
        "        email: data.email,",
        "        password: hashedPassword,",
        "        emailVerificationToken,",
        "      },",
        "    });",
        "",
        "    await emailService.sendVerificationEmail(user.email, emailVerificationToken);",
        "    const token = generateToken({ id: user.id, email: user.email });",
        "    return { message: 'Registration successful. Please verify your email.', token };",
        "  }",
        "",
        "  async login(data: LoginInput) {",
        "    const user = await prisma.user.findUnique({ where: { email: data.email } });",
        "    if (!user) throw Object.assign(new Error('Invalid credentials'), { status: 401 });",
        "",
        "    const valid = await bcrypt.compare(data.password, user.password);",
        "    if (!valid) throw Object.assign(new Error('Invalid credentials'), { status: 401 });",
        "",
        "    if (user.twoFactorEnabled) {",
        "      if (!data.twoFactorCode) return { message: '2FA code required', requires2FA: true };",
        "      const verified = verifyTwoFactorToken(user.twoFactorSecret ?? '', data.twoFactorCode);",
        "      if (!verified) throw Object.assign(new Error('Invalid 2FA code'), { status: 401 });",
        "    }",
        "",
        "    const token = generateToken({ id: user.id, email: user.email });",
        "    return { message: 'Login successful', token };",
        "  }",
        "",
        "  async forgotPassword(data: { email: string }) {",
        "    const user = await prisma.user.findUnique({ where: { email: data.email } });",
        "    if (!user) return { message: 'If the email exists, a reset link has been sent.' };",
        "",
        "    const resetPasswordToken = crypto.randomBytes(32).toString('hex');",
        "    await prisma.user.update({",
        "      where: { id: user.id },",
        "      data: {",
        "        resetPasswordToken,",
        "        resetPasswordExpires: new Date(Date.now() + 3600000),",
        "      },",
        "    });",
        "",
        "    await emailService.sendPasswordResetEmail(user.email, resetPasswordToken);",
        "    return { message: 'If the email exists, a reset link has been sent.' };",
        "  }",
        "",
        "  async resetPassword(data: { token: string; newPassword: string }) {",
        "    const user = await prisma.user.findFirst({",
        "      where: {",
        "        resetPasswordToken: data.token,",
        "        resetPasswordExpires: { gt: new Date() },",
        "      },",
        "    });",
        "    if (!user) throw Object.assign(new Error('Invalid or expired reset token'), { status: 400 });",
        "",
        "    await prisma.user.update({",
        "      where: { id: user.id },",
        "      data: {",
        "        password: await bcrypt.hash(data.newPassword, 12),",
        "        resetPasswordToken: null,",
        "        resetPasswordExpires: null,",
        "      },",
        "    });",
        "",
        "    return { message: 'Password has been reset successfully' };",
        "  }",
        "",
        "  async verifyEmail(data: { token: string }) {",
        "    const user = await prisma.user.findFirst({",
        "      where: { emailVerificationToken: data.token },",
        "    });",
        "    if (!user) throw Object.assign(new Error('Invalid verification token'), { status: 400 });",
        "",
        "    await prisma.user.update({",
        "      where: { id: user.id },",
        "      data: { emailVerified: true, emailVerificationToken: null },",
        "    });",
        "",
        "    return { message: 'Email verified successfully' };",
        "  }",
        "",
        "  async setupTwoFactor(userId: string) {",
        "    const user = await prisma.user.findUnique({ where: { id: userId } });",
        "    if (!user) throw Object.assign(new Error('User not found'), { status: 404 });",
        "",
        "    const { secret, qrCode } = await setupTwoFactor(user.email);",
        "    await prisma.user.update({ where: { id: user.id }, data: { twoFactorSecret: secret } });",
        "    return { secret, qrCode };",
        "  }",
        "",
        "  async verifyTwoFactor(userId: string, code: string) {",
        "    const user = await prisma.user.findUnique({ where: { id: userId } });",
        "    if (!user?.twoFactorSecret) throw Object.assign(new Error('2FA not set up'), { status: 400 });",
        "",
        "    const verified = verifyTwoFactorToken(user.twoFactorSecret, code);",
        "    if (!verified) throw Object.assign(new Error('Invalid 2FA code'), { status: 400 });",
        "",
        "    await prisma.user.update({",
        "      where: { id: user.id },",
        "      data: { twoFactorEnabled: true },",
        "    });",
        "",
        "    return { message: '2FA enabled successfully' };",
        "  }",
        "}",
      ),
    },
    {
      path: 'src/services/email.service.ts',
      content: lines(
        "import nodemailer from 'nodemailer';",
        "",
        "export class EmailService {",
        "  private transporter = nodemailer.createTransport({",
        "    host: process.env.SMTP_HOST ?? 'smtp.ethereal.email',",
        "    port: Number(process.env.SMTP_PORT ?? 587),",
        "    secure: false,",
        "    auth: {",
        "      user: process.env.SMTP_USER ?? 'demo@example.com',",
        "      pass: process.env.SMTP_PASS ?? 'demo-password',",
        "    },",
        "  });",
        "",
        "  async sendVerificationEmail(email: string, token: string) {",
        "    await this.transporter.sendMail({",
        "      to: email,",
        "      subject: 'Verify your email',",
        "      text: `Verification token: ${token}`,",
        "    });",
        "  }",
        "",
        "  async sendPasswordResetEmail(email: string, token: string) {",
        "    await this.transporter.sendMail({",
        "      to: email,",
        "      subject: 'Reset your password',",
        "      text: `Reset token: ${token}`,",
        "    });",
        "  }",
        "}",
      ),
    },
    {
      path: 'src/config/prisma.ts',
      content: lines(
        "import { PrismaClient } from '@prisma/client';",
        "",
        "declare global {",
        "  // eslint-disable-next-line no-var",
        "  var __prisma__: PrismaClient | undefined;",
        "}",
        "",
        "export const prisma = globalThis.__prisma__ ?? new PrismaClient();",
        "",
        "if (process.env.NODE_ENV !== 'production') {",
        "  globalThis.__prisma__ = prisma;",
        "}",
      ),
    },
    {
      path: 'src/config/env.ts',
      content: lines(
        "export const env = {",
        "  port: Number(process.env.PORT ?? 3001),",
        "  jwtSecret: process.env.JWT_SECRET ?? 'change-me-in-production',",
        "  databaseUrl: process.env.DATABASE_URL ?? '',",
        "};",
      ),
    },
    {
      path: 'src/interfaces/auth-request.interface.ts',
      content: lines(
        "import type { Request } from 'express';",
        "",
        "export interface AuthUserPayload {",
        "  id: string;",
        "  email: string;",
        "}",
        "",
        "export interface AuthenticatedRequest extends Request {",
        "  user?: AuthUserPayload;",
        "}",
      ),
    },
    {
      path: 'src/middleware/auth.middleware.ts',
      content: lines(
        "import type { NextFunction, Response } from 'express';",
        "import jwt from 'jsonwebtoken';",
        "import type { AuthenticatedRequest } from '@/interfaces/auth-request.interface';",
        "",
        "export function authMiddleware(req: AuthenticatedRequest, res: Response, next: NextFunction) {",
        "  const header = req.headers.authorization;",
        "  const token = header?.startsWith('Bearer ') ? header.slice(7) : undefined;",
        "",
        "  if (!token) {",
        "    res.status(401).json({ message: 'Missing authentication token' });",
        "    return;",
        "  }",
        "",
        "  try {",
        "    const payload = jwt.verify(token, process.env.JWT_SECRET ?? 'change-me-in-production') as { id: string; email: string };",
        "    req.user = { id: payload.id, email: payload.email };",
        "    next();",
        "  } catch {",
        "    res.status(401).json({ message: 'Invalid authentication token' });",
        "  }",
        "}",
      ),
    },
    {
      path: 'src/middleware/error.middleware.ts',
      content: lines(
        "import type { NextFunction, Request, Response } from 'express';",
        "",
        "export function errorHandler(err: Error & { status?: number }, _req: Request, res: Response, _next: NextFunction) {",
        "  res.status(err.status ?? 500).json({",
        "    message: err.message || 'Internal server error',",
        "  });",
        "}",
      ),
    },
    {
      path: 'src/middleware/validate.middleware.ts',
      content: lines(
        "import type { NextFunction, Request, Response } from 'express';",
        "import type { ZodSchema } from 'zod';",
        "",
        "export function validate(schema: ZodSchema) {",
        "  return (req: Request, res: Response, next: NextFunction) => {",
        "    const result = schema.safeParse(req.body);",
        "    if (!result.success) {",
        "      res.status(400).json({ message: 'Validation failed', issues: result.error.flatten() });",
        "      return;",
        "    }",
        "",
        "    req.body = result.data;",
        "    next();",
        "  };",
        "}",
      ),
    },
    {
      path: 'src/schemas/auth.schema.ts',
      content: lines(
        "import { z } from 'zod';",
        "",
        "export const registerSchema = z.object({",
        "  name: z.string().min(2),",
        "  email: z.string().email(),",
        "  password: z.string().min(8),",
        "});",
        "",
        "export const loginSchema = z.object({",
        "  email: z.string().email(),",
        "  password: z.string().min(8),",
        "  twoFactorCode: z.string().optional(),",
        "});",
        "",
        "export const forgotPasswordSchema = z.object({",
        "  email: z.string().email(),",
        "});",
        "",
        "export const resetPasswordSchema = z.object({",
        "  token: z.string().min(1),",
        "  newPassword: z.string().min(8),",
        "});",
        "",
        "export const verifyEmailSchema = z.object({",
        "  token: z.string().min(1),",
        "});",
        "",
        "export const twoFactorSchema = z.object({",
        "  code: z.string().min(6),",
        "});",
        "",
        "export type RegisterInput = z.infer<typeof registerSchema>;",
        "export type LoginInput = z.infer<typeof loginSchema>;",
      ),
    },
    {
      path: 'src/utils/token.util.ts',
      content: lines(
        "import jwt from 'jsonwebtoken';",
        "",
        "export function generateToken(payload: { id: string; email: string }) {",
        "  return jwt.sign(payload, process.env.JWT_SECRET ?? 'change-me-in-production', {",
        "    expiresIn: '1h',",
        "  });",
        "}",
      ),
    },
    {
      path: 'src/utils/two-factor.util.ts',
      content: lines(
        "import QRCode from 'qrcode';",
        "import speakeasy from 'speakeasy';",
        "",
        "export async function setupTwoFactor(email: string) {",
        "  const secret = speakeasy.generateSecret({ name: `forgeflux:${email}` });",
        "  const qrCode = await QRCode.toDataURL(secret.otpauth_url ?? '');",
        "  return { secret: secret.base32, qrCode };",
        "}",
        "",
        "export function verifyTwoFactorToken(secret: string, token: string) {",
        "  return speakeasy.totp.verify({ secret, encoding: 'base32', token });",
        "}",
      ),
    },
    {
      path: 'src/types/express.d.ts',
      content: lines(
        "declare namespace Express {",
        "  interface UserPayload {",
        "    id: string;",
        "    email: string;",
        "  }",
        "",
        "  interface Request {",
        "    user?: UserPayload;",
        "  }",
        "}",
      ),
    },
  ];
}
