interface TemplateFile {
  path: string;
  content: string;
}

function lines(...value: string[]): string {
  return `${value.join('\n')}\n`;
}

export function getNestAuthFiles(name: string): TemplateFile[] {
  return [
    {
      path: 'src/main.ts',
      content: lines(
        "import 'reflect-metadata';",
        "import { ValidationPipe } from '@nestjs/common';",
        "import { NestFactory } from '@nestjs/core';",
        "import { AppModule } from '@/app.module';",
        "",
        "async function bootstrap() {",
        "  const app = await NestFactory.create(AppModule);",
        "  app.enableCors();",
        "  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));",
        "  const port = Number(process.env.PORT ?? 3000);",
        "  await app.listen(port);",
        `  console.log('${name} running on http://localhost:' + port);`,
        "}",
        "",
        "void bootstrap();",
      ),
    },
    {
      path: 'src/app.module.ts',
      content: lines(
        "import { Module } from '@nestjs/common';",
        "import { PrismaModule } from '@/modules/prisma/prisma.module';",
        "import { AuthModule } from '@/modules/auth/auth.module';",
        "import { HealthController } from '@/modules/health/health.controller';",
        "",
        "@Module({",
        "  imports: [PrismaModule, AuthModule],",
        "  controllers: [HealthController],",
        "})",
        "export class AppModule {}",
      ),
    },
    {
      path: 'src/modules/health/health.controller.ts',
      content: lines(
        "import { Controller, Get } from '@nestjs/common';",
        "",
        "@Controller('health')",
        "export class HealthController {",
        "  @Get()",
        "  check() {",
        "    return { status: 'ok' };",
        "  }",
        "}",
      ),
    },
    {
      path: 'src/modules/prisma/prisma.module.ts',
      content: lines(
        "import { Global, Module } from '@nestjs/common';",
        "import { PrismaService } from '@/modules/prisma/prisma.service';",
        "",
        "@Global()",
        "@Module({",
        "  providers: [PrismaService],",
        "  exports: [PrismaService],",
        "})",
        "export class PrismaModule {}",
      ),
    },
    {
      path: 'src/modules/prisma/prisma.service.ts',
      content: lines(
        "import { Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common';",
        "import { PrismaClient } from '@prisma/client';",
        "",
        "@Injectable()",
        "export class PrismaService extends PrismaClient implements OnModuleInit, OnModuleDestroy {",
        "  async onModuleInit() {",
        "    await this.$connect();",
        "  }",
        "",
        "  async onModuleDestroy() {",
        "    await this.$disconnect();",
        "  }",
        "}",
      ),
    },
    {
      path: 'src/modules/auth/auth.module.ts',
      content: lines(
        "import { Module } from '@nestjs/common';",
        "import { JwtModule } from '@nestjs/jwt';",
        "import { PassportModule } from '@nestjs/passport';",
        "import { EmailService } from '@/common/services/email.service';",
        "import { AuthController } from '@/modules/auth/auth.controller';",
        "import { AuthService } from '@/modules/auth/auth.service';",
        "import { JwtAuthGuard } from '@/modules/auth/guards/jwt-auth.guard';",
        "import { JwtStrategy } from '@/modules/auth/strategies/jwt.strategy';",
        "",
        "@Module({",
        "  imports: [",
        "    PassportModule.register({ defaultStrategy: 'jwt' }),",
        "    JwtModule.register({",
        "      secret: process.env.JWT_SECRET ?? 'change-me-in-production',",
        "      signOptions: { expiresIn: '1h' },",
        "    }),",
        "  ],",
        "  controllers: [AuthController],",
        "  providers: [AuthService, JwtStrategy, JwtAuthGuard, EmailService],",
        "  exports: [AuthService],",
        "})",
        "export class AuthModule {}",
      ),
    },
    {
      path: 'src/modules/auth/auth.controller.ts',
      content: lines(
        "import { Body, Controller, HttpCode, HttpStatus, Post, Req, UseGuards } from '@nestjs/common';",
        "import type { AuthenticatedRequest } from '@/modules/auth/interfaces/authenticated-request.interface';",
        "import { AuthService } from '@/modules/auth/auth.service';",
        "import { ForgotPasswordDto } from '@/modules/auth/dto/forgot-password.dto';",
        "import { LoginDto } from '@/modules/auth/dto/login.dto';",
        "import { RegisterDto } from '@/modules/auth/dto/register.dto';",
        "import { ResetPasswordDto } from '@/modules/auth/dto/reset-password.dto';",
        "import { TwoFactorDto } from '@/modules/auth/dto/two-factor.dto';",
        "import { VerifyEmailDto } from '@/modules/auth/dto/verify-email.dto';",
        "import { JwtAuthGuard } from '@/modules/auth/guards/jwt-auth.guard';",
        "",
        "@Controller('auth')",
        "export class AuthController {",
        "  constructor(private readonly authService: AuthService) {}",
        "",
        "  @Post('register')",
        "  async register(@Body() dto: RegisterDto) {",
        "    return this.authService.register(dto);",
        "  }",
        "",
        "  @Post('login')",
        "  @HttpCode(HttpStatus.OK)",
        "  async login(@Body() dto: LoginDto) {",
        "    return this.authService.login(dto);",
        "  }",
        "",
        "  @Post('forgot-password')",
        "  @HttpCode(HttpStatus.OK)",
        "  async forgotPassword(@Body() dto: ForgotPasswordDto) {",
        "    return this.authService.forgotPassword(dto);",
        "  }",
        "",
        "  @Post('reset-password')",
        "  @HttpCode(HttpStatus.OK)",
        "  async resetPassword(@Body() dto: ResetPasswordDto) {",
        "    return this.authService.resetPassword(dto);",
        "  }",
        "",
        "  @Post('verify-email')",
        "  @HttpCode(HttpStatus.OK)",
        "  async verifyEmail(@Body() dto: VerifyEmailDto) {",
        "    return this.authService.verifyEmail(dto);",
        "  }",
        "",
        "  @Post('2fa/setup')",
        "  @UseGuards(JwtAuthGuard)",
        "  async setupTwoFactor(@Req() req: AuthenticatedRequest) {",
        "    return this.authService.setupTwoFactor(req.user.id);",
        "  }",
        "",
        "  @Post('2fa/verify')",
        "  @UseGuards(JwtAuthGuard)",
        "  async verifyTwoFactor(@Req() req: AuthenticatedRequest, @Body() dto: TwoFactorDto) {",
        "    return this.authService.verifyTwoFactor(req.user.id, dto.code);",
        "  }",
        "}",
      ),
    },
    {
      path: 'src/modules/auth/auth.service.ts',
      content: lines(
        "import { BadRequestException, Injectable, UnauthorizedException } from '@nestjs/common';",
        "import { JwtService } from '@nestjs/jwt';",
        "import * as bcrypt from 'bcrypt';",
        "import * as crypto from 'node:crypto';",
        "import * as QRCode from 'qrcode';",
        "import * as speakeasy from 'speakeasy';",
        "import { EmailService } from '@/common/services/email.service';",
        "import { ForgotPasswordDto } from '@/modules/auth/dto/forgot-password.dto';",
        "import { LoginDto } from '@/modules/auth/dto/login.dto';",
        "import { RegisterDto } from '@/modules/auth/dto/register.dto';",
        "import { ResetPasswordDto } from '@/modules/auth/dto/reset-password.dto';",
        "import { VerifyEmailDto } from '@/modules/auth/dto/verify-email.dto';",
        "import { PrismaService } from '@/modules/prisma/prisma.service';",
        "",
        "@Injectable()",
        "export class AuthService {",
        "  constructor(",
        "    private readonly jwtService: JwtService,",
        "    private readonly prisma: PrismaService,",
        "    private readonly emailService: EmailService,",
        "  ) {}",
        "",
        "  async register(dto: RegisterDto) {",
        "    const existing = await this.prisma.user.findUnique({ where: { email: dto.email } });",
        "    if (existing) throw new BadRequestException('Email already registered');",
        "",
        "    const hashedPassword = await bcrypt.hash(dto.password, 12);",
        "    const emailVerificationToken = crypto.randomBytes(32).toString('hex');",
        "",
        "    const user = await this.prisma.user.create({",
        "      data: {",
        "        name: dto.name,",
        "        email: dto.email,",
        "        password: hashedPassword,",
        "        emailVerificationToken,",
        "      },",
        "    });",
        "",
        "    await this.emailService.sendVerificationEmail(user.email, emailVerificationToken);",
        "    const token = this.jwtService.sign({ id: user.id, email: user.email });",
        "    return { message: 'Registration successful. Please verify your email.', token };",
        "  }",
        "",
        "  async login(dto: LoginDto) {",
        "    const user = await this.prisma.user.findUnique({ where: { email: dto.email } });",
        "    if (!user) throw new UnauthorizedException('Invalid credentials');",
        "",
        "    const valid = await bcrypt.compare(dto.password, user.password);",
        "    if (!valid) throw new UnauthorizedException('Invalid credentials');",
        "",
        "    if (user.twoFactorEnabled) {",
        "      if (!dto.twoFactorCode) return { message: '2FA code required', requires2FA: true };",
        "      const verified = speakeasy.totp.verify({",
        "        secret: user.twoFactorSecret ?? '',",
        "        encoding: 'base32',",
        "        token: dto.twoFactorCode,",
        "      });",
        "      if (!verified) throw new UnauthorizedException('Invalid 2FA code');",
        "    }",
        "",
        "    const token = this.jwtService.sign({ id: user.id, email: user.email });",
        "    return { message: 'Login successful', token };",
        "  }",
        "",
        "  async forgotPassword(dto: ForgotPasswordDto) {",
        "    const user = await this.prisma.user.findUnique({ where: { email: dto.email } });",
        "    if (!user) return { message: 'If the email exists, a reset link has been sent.' };",
        "",
        "    const resetPasswordToken = crypto.randomBytes(32).toString('hex');",
        "    await this.prisma.user.update({",
        "      where: { id: user.id },",
        "      data: {",
        "        resetPasswordToken,",
        "        resetPasswordExpires: new Date(Date.now() + 3600000),",
        "      },",
        "    });",
        "",
        "    await this.emailService.sendPasswordResetEmail(user.email, resetPasswordToken);",
        "    return { message: 'If the email exists, a reset link has been sent.' };",
        "  }",
        "",
        "  async resetPassword(dto: ResetPasswordDto) {",
        "    const user = await this.prisma.user.findFirst({",
        "      where: {",
        "        resetPasswordToken: dto.token,",
        "        resetPasswordExpires: { gt: new Date() },",
        "      },",
        "    });",
        "    if (!user) throw new BadRequestException('Invalid or expired reset token');",
        "",
        "    await this.prisma.user.update({",
        "      where: { id: user.id },",
        "      data: {",
        "        password: await bcrypt.hash(dto.newPassword, 12),",
        "        resetPasswordToken: null,",
        "        resetPasswordExpires: null,",
        "      },",
        "    });",
        "",
        "    return { message: 'Password has been reset successfully' };",
        "  }",
        "",
        "  async verifyEmail(dto: VerifyEmailDto) {",
        "    const user = await this.prisma.user.findFirst({",
        "      where: { emailVerificationToken: dto.token },",
        "    });",
        "    if (!user) throw new BadRequestException('Invalid verification token');",
        "",
        "    await this.prisma.user.update({",
        "      where: { id: user.id },",
        "      data: { emailVerified: true, emailVerificationToken: null },",
        "    });",
        "",
        "    return { message: 'Email verified successfully' };",
        "  }",
        "",
        "  async setupTwoFactor(userId: string) {",
        "    const user = await this.prisma.user.findUnique({ where: { id: userId } });",
        "    if (!user) throw new BadRequestException('User not found');",
        "",
        "    const secret = speakeasy.generateSecret({ name: `forgeflux:${user.email}` });",
        "    await this.prisma.user.update({",
        "      where: { id: user.id },",
        "      data: { twoFactorSecret: secret.base32 },",
        "    });",
        "",
        "    const qrCode = await QRCode.toDataURL(secret.otpauth_url ?? '');",
        "    return { secret: secret.base32, qrCode };",
        "  }",
        "",
        "  async verifyTwoFactor(userId: string, code: string) {",
        "    const user = await this.prisma.user.findUnique({ where: { id: userId } });",
        "    if (!user?.twoFactorSecret) throw new BadRequestException('2FA not set up');",
        "",
        "    const verified = speakeasy.totp.verify({",
        "      secret: user.twoFactorSecret,",
        "      encoding: 'base32',",
        "      token: code,",
        "    });",
        "    if (!verified) throw new BadRequestException('Invalid 2FA code');",
        "",
        "    await this.prisma.user.update({",
        "      where: { id: user.id },",
        "      data: { twoFactorEnabled: true },",
        "    });",
        "",
        "    return { message: '2FA enabled successfully' };",
        "  }",
        "}",
      ),
    },
    {
      path: 'src/modules/auth/dto/register.dto.ts',
      content: lines(
        "import { IsEmail, IsString, MinLength } from 'class-validator';",
        "",
        "export class RegisterDto {",
        "  @IsString()",
        "  @MinLength(2)",
        "  name!: string;",
        "",
        "  @IsEmail()",
        "  email!: string;",
        "",
        "  @IsString()",
        "  @MinLength(8)",
        "  password!: string;",
        "}",
      ),
    },
    {
      path: 'src/modules/auth/dto/login.dto.ts',
      content: lines(
        "import { IsEmail, IsOptional, IsString, MinLength } from 'class-validator';",
        "",
        "export class LoginDto {",
        "  @IsEmail()",
        "  email!: string;",
        "",
        "  @IsString()",
        "  @MinLength(8)",
        "  password!: string;",
        "",
        "  @IsOptional()",
        "  @IsString()",
        "  twoFactorCode?: string;",
        "}",
      ),
    },
    {
      path: 'src/modules/auth/dto/forgot-password.dto.ts',
      content: lines(
        "import { IsEmail } from 'class-validator';",
        "",
        "export class ForgotPasswordDto {",
        "  @IsEmail()",
        "  email!: string;",
        "}",
      ),
    },
    {
      path: 'src/modules/auth/dto/reset-password.dto.ts',
      content: lines(
        "import { IsString, MinLength } from 'class-validator';",
        "",
        "export class ResetPasswordDto {",
        "  @IsString()",
        "  token!: string;",
        "",
        "  @IsString()",
        "  @MinLength(8)",
        "  newPassword!: string;",
        "}",
      ),
    },
    {
      path: 'src/modules/auth/dto/verify-email.dto.ts',
      content: lines(
        "import { IsString } from 'class-validator';",
        "",
        "export class VerifyEmailDto {",
        "  @IsString()",
        "  token!: string;",
        "}",
      ),
    },
    {
      path: 'src/modules/auth/dto/two-factor.dto.ts',
      content: lines(
        "import { IsString, MinLength } from 'class-validator';",
        "",
        "export class TwoFactorDto {",
        "  @IsString()",
        "  @MinLength(6)",
        "  code!: string;",
        "}",
      ),
    },
    {
      path: 'src/modules/auth/guards/jwt-auth.guard.ts',
      content: lines(
        "import { Injectable } from '@nestjs/common';",
        "import { AuthGuard } from '@nestjs/passport';",
        "",
        "@Injectable()",
        "export class JwtAuthGuard extends AuthGuard('jwt') {}",
      ),
    },
    {
      path: 'src/modules/auth/interfaces/authenticated-request.interface.ts',
      content: lines(
        "export interface AuthenticatedRequest {",
        "  user: {",
        "    id: string;",
        "    email: string;",
        "  };",
        "}",
      ),
    },
    {
      path: 'src/modules/auth/strategies/jwt.strategy.ts',
      content: lines(
        "import { Injectable } from '@nestjs/common';",
        "import { PassportStrategy } from '@nestjs/passport';",
        "import { ExtractJwt, Strategy } from 'passport-jwt';",
        "",
        "@Injectable()",
        "export class JwtStrategy extends PassportStrategy(Strategy) {",
        "  constructor() {",
        "    super({",
        "      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),",
        "      ignoreExpiration: false,",
        "      secretOrKey: process.env.JWT_SECRET ?? 'change-me-in-production',",
        "    });",
        "  }",
        "",
        "  async validate(payload: { id: string; email: string }) {",
        "    return payload;",
        "  }",
        "}",
      ),
    },
    {
      path: 'src/common/services/email.service.ts',
      content: lines(
        "import { Injectable } from '@nestjs/common';",
        "import * as nodemailer from 'nodemailer';",
        "",
        "@Injectable()",
        "export class EmailService {",
        "  private transporter = nodemailer.createTransport({",
        "    host: process.env.SMTP_HOST ?? 'smtp.ethereal.email',",
        "    port: Number(process.env.SMTP_PORT ?? 587),",
        "    secure: false,",
        "    auth: {",
        "      user: process.env.SMTP_USER ?? 'demo@example.com',",
        "      pass: process.env.SMTP_PASS ?? 'demo-password',",
        "    },",
        "  });",
        "",
        "  async sendVerificationEmail(email: string, token: string) {",
        "    await this.transporter.sendMail({",
        "      to: email,",
        "      subject: 'Verify your email',",
        "      text: `Verification token: ${token}`,",
        "    });",
        "  }",
        "",
        "  async sendPasswordResetEmail(email: string, token: string) {",
        "    await this.transporter.sendMail({",
        "      to: email,",
        "      subject: 'Reset your password',",
        "      text: `Reset token: ${token}`,",
        "    });",
        "  }",
        "}",
      ),
    },
  ];
}
