import fs from 'node:fs';
import path from 'node:path';
import fsExtra from 'fs-extra';

export type ProjectType = 'npm' | 'vscode' | 'wordpress' | 'shopify';

export interface ScaffoldOptions {
  type: ProjectType;
  name: string;
  outputDir?: string;
}

export interface LintOptions {
  dir?: string;
}

export interface AuditOptions {
  dir?: string;
}

export interface CommandResult {
  success: boolean;
  message: string;
}

const scaffoldBlueprints: Record<ProjectType, string[]> = {
  npm: [
    'src/index.ts',
    'tests/index.test.ts',
    '.eslintrc.json',
    '.prettierrc',
    'tsconfig.json',
    'rollup.config.js',
    'package.json',
    'README.md'
  ],
  vscode: [
    'src/extension.ts',
    '.vscode/extensions.json',
    'package.json',
    'tsconfig.json',
    'README.md'
  ],
  wordpress: [
    'includes/bootstrap.php',
    'admin/admin.php',
    'public/public.php',
    'plugin.php',
    '.phpcs.xml',
    'composer.json',
    'README.md'
  ],
  shopify: [
    'app/routes/index.tsx',
    'app/shopify.server.ts',
    'prisma/schema.prisma',
    'public/favicon.svg',
    'shopify.app.toml',
    'package.json',
    'README.md'
  ]
};

function unique<T>(value: T, index: number, items: T[]): boolean {
  return items.indexOf(value) === index;
}

function toAbsoluteDir(dir?: string): string {
  return path.resolve(dir ?? process.cwd());
}

function parentDirs(files: string[]): string[] {
  return files
    .map((file) => path.dirname(file))
    .filter((dir) => dir !== '.')
    .filter(unique);
}

export async function scaffold(options: ScaffoldOptions): Promise<CommandResult> {
  const baseDir = path.resolve(options.outputDir ?? process.cwd(), options.name);
  const blueprint = scaffoldBlueprints[options.type];

  await fsExtra.ensureDir(baseDir);
  await Promise.all(
    parentDirs(blueprint).map((dir) => fsExtra.ensureDir(path.join(baseDir, dir)))
  );

  await Promise.all(
    blueprint.map(async (file) => {
      const fullPath = path.join(baseDir, file);
      if (!(await fsExtra.pathExists(fullPath))) {
        await fsExtra.writeFile(
          fullPath,
          `# ${options.name}\n\nGenerated by devforge-cli for ${options.type}.\n`
        );
      }
    })
  );

  return {
    success: true,
    message: `Scaffolded ${options.type} project at ${baseDir}`
  };
}

export async function lint(options: LintOptions = {}): Promise<CommandResult> {
  const dir = toAbsoluteDir(options.dir);
  const packageJsonExists = fs.existsSync(path.join(dir, 'package.json'));

  return {
    success: packageJsonExists,
    message: packageJsonExists
      ? `Lint configuration check passed for ${dir}`
      : `No package.json found in ${dir}`
  };
}

export async function audit(options: AuditOptions = {}): Promise<CommandResult> {
  const dir = toAbsoluteDir(options.dir);
  const packageJsonPath = path.join(dir, 'package.json');

  if (!fs.existsSync(packageJsonPath)) {
    return {
      success: false,
      message: `No package.json found in ${dir}`
    };
  }

  const packageJson = await fsExtra.readJson(packageJsonPath);
  const deps = {
    ...(packageJson.dependencies ?? {}),
    ...(packageJson.devDependencies ?? {})
  };

  return {
    success: true,
    message: `Found ${Object.keys(deps).length} dependencies in ${dir}`
  };
}
